# Generated by Django 4.2.16 on 2024-11-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_post_image_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(related_name='users', to='core.tag', verbose_name='Тэги'),
        ),
    ]
