# Generated by Django 4.2.16 on 2024-11-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_tags_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='core.tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Уникальный индентификатор telegram'),
        ),
    ]
