# Generated by Django 4.2.16 on 2024-11-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_tags_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.tag', verbose_name='Тэги'),
        ),
    ]
