# Generated by Django 3.2.3 on 2025-02-27 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('blog', '0002_rename_text_url_news_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.URLField(verbose_name='Ссылка на фото новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_url',
            field=models.URLField(verbose_name='Ссылка на новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата публикации новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(max_length=100, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='users.tag'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='ShortNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Главная мысль сжатой новости')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации новости')),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_news', to='blog.news')),
            ],
            options={
                'verbose_name': 'сжатая новость',
                'verbose_name_plural': 'Сжатые новости',
                'ordering': ('pub_date',),
                'default_related_name': 'short_news',
            },
        ),
    ]
