# Generated by Django 3.2.3 on 2025-03-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20250227_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_url',
            field=models.URLField(db_index=True, verbose_name='Ссылка на новость'),
        ),
        migrations.AlterField(
            model_name='shortnews',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации новости'),
        ),
    ]
